// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqkzyzlyrkxatgdqjczz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxa3p5emx5cmt4YXRnZHFqY3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTExNzgsImV4cCI6MjA2NTU4NzE3OH0.0lPyU9Ds0RlnmF36N3qitzCLx0z3xsnc0DI7fFpPmF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);